version: '3.9'

services:
  production-verification-frontend-production:
    image: manulrnd/production-verification-frontend:production
    build:
      dockerfile: ./client/Dockerfile
      args:
        DOCKER_BUILDKIT: 1
    volumes:
      - pv-frontend-prod:/app/build
      - pnpm-store-prod:/pnpm-store
    environment:
      - NODE_ENV=production

  nginx-production:
    image: nginx:latest
    container_name: pv-nginx-production
    ports:
      - "90:80"
    volumes:
      - ./conf/production/nginx.conf:/etc/nginx/nginx.conf:ro
      - pv-frontend-prod:/usr/share/nginx/html
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - production-verification-frontend-production

volumes:
  pv-frontend-prod:
  pnpm-store-prod:
