name: Profuction Verification frontend to Staging server
# hehehe
on:
  pull_request:
    branches:
      - stage
    paths:
      - "client/**"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [stage, pv-stage]
    steps:
      - name: Set up repository
        uses: actions/checkout@v2

      - name: Log in to Docker
        run: echo "${{ secrets.DOCKER_PASS }}" | docker login -u "${{ secrets.DOCKER_LOGIN }}" --password-stdin

      - name: Stop and remove containers
        run: |
          docker system prune -f
          docker compose -f docker-compose-staging.yml down --volumes
          docker compose -f docker-compose-staging.yml rm -f
          docker images --filter "dangling=true" -q | xargs -r docker rmi -f
          docker volume ls -qf dangling=true | xargs -r docker volume rm

      - name: Build and start Docker images
        run: |
          docker compose -f docker-compose-staging.yml build --no-cache
          docker compose -f docker-compose-staging.yml up -d
