name: Profuction Verification frontend to Test Staging server
# hehehe
on:
  pull_request:
    branches:
      - stage
    paths:
      - "client/**"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [stage]
    steps:
      - name: "Trigger jenkins job"
        uses: umutcolak/jenkins-trigger-job@main
        with:
          jenkins-url: "http://172.25.142.178:8080"
          user: "admin"
          jenkins-token: ${{secrets.JENKINS_TOKEN}}
          job-name: "test-pv-stage"
          job-params: '{"branch_name": "${{github.ref}}"}'
